import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Input from './_input'
import Video from './_video'
import Form from './_form'
import { AiFillHeart } from 'react-icons/ai'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp"/>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" defer></script>
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Video></Video>
        </div>
        <div className={styles.input}>
          <Input />
          <Form></Form>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className='footer'>© 2023 Copyright: Cinthia Orona. Made with {' '}
          <a><AiFillHeart /></a>
        </div>
      </footer>
    </>
  )
}
